import { useState } from 'react'
import { maybeDefang } from '../utils/defang'

export function buildReport(result, defangOn = false) {
  const pr = result.provider_results || []
  const vtResult = pr.find(p => p.provider === 'virustotal')
  const abuseResult = pr.find(p => p.provider === 'abuseipdb')

  const lines = [
    '═══════════════════════════════════════',
    '           BULK-IOC-SCANNER REPORT            ',
    '═══════════════════════════════════════',
    `IOC:         ${maybeDefang(result.ioc, defangOn)}`,
    `Type:        ${result.ioc_type?.toUpperCase() || 'UNKNOWN'}`,
    `Risk:        ${result.risk_band || 'N/A'} (${result.risk_score ?? 'N/A'}/100)`,
    `Detection:   ${result.detection_ratio || 'N/A'}`,
    '',
  ]

  if (vtResult?.success) {
    lines.push('── VirusTotal ──────────────────────────')
    if (vtResult.raw?.file_name) lines.push(`File Name:   ${vtResult.raw.file_name}`)
    if (vtResult.raw?.file_type) lines.push(`File Type:   ${vtResult.raw.file_type}`)
    if (vtResult.raw?.first_seen) lines.push(`First Seen:  ${vtResult.raw.first_seen}`)
    if (vtResult.raw?.last_analysis) lines.push(`Last Scan:   ${vtResult.raw.last_analysis}`)
    if (vtResult.raw?.country) lines.push(`Country:     ${vtResult.raw.country}`)
    if (vtResult.raw?.as_owner) lines.push(`ASN Owner:   ${vtResult.raw.as_owner}`)
    if (vtResult.raw?.reputation != null) lines.push(`Reputation:  ${vtResult.raw.reputation}`)
    lines.push('')
  }

  if (abuseResult?.success) {
    lines.push('── AbuseIPDB ───────────────────────────')
    const r = abuseResult.raw || {}
    if (r.country_code) lines.push(`Country:     ${r.country_code}`)
    if (r.isp) lines.push(`ISP:         ${r.isp}`)
    if (r.abuse_confidence_score != null) lines.push(`Confidence:  ${r.abuse_confidence_score}%`)
    if (r.total_reports != null) lines.push(`Reports:     ${r.total_reports}`)
    if (r.is_tor) lines.push(`TOR Node:    YES`)
    lines.push('')
  }

  const errors = pr.filter(p => !p.success).map(p => `${p.provider}: ${p.error}`)
  if (errors.length) {
    lines.push('── Provider Errors ─────────────────────')
    errors.forEach(e => lines.push(e))
    lines.push('')
  }

  lines.push('── Recommended Action ──────────────────')
  if (result.risk_band === 'High') {
    lines.push('⚠ BLOCK / QUARANTINE — High malicious detection rate')
  } else if (result.risk_band === 'Medium') {
    lines.push('⚠ INVESTIGATE — Suspicious activity detected')
  } else {
    lines.push('✓ LOW RISK — No significant detections')
  }

  lines.push('')
  lines.push(`Generated by Bulk-IOC-Scanner · ${new Date().toISOString()}`)
  lines.push('═══════════════════════════════════════')

  return lines.join('\n')
}

export default function CopyReportButton({ result }) {
  const [copied, setCopied] = useState(false)
  const [defangOn, setDefangOn] = useState(false)

  async function handleCopy() {
    const text = buildReport(result, defangOn)
    try {
      await navigator.clipboard.writeText(text)
      setCopied(true)
      setTimeout(() => setCopied(false), 2000)
    } catch {
      // fallback
      const ta = document.createElement('textarea')
      ta.value = text
      document.body.appendChild(ta)
      ta.select()
      document.execCommand('copy')
      document.body.removeChild(ta)
      setCopied(true)
      setTimeout(() => setCopied(false), 2000)
    }
  }

  return (
    <div className="flex items-center gap-3">
      <label className="flex items-center gap-1 text-xs font-mono text-slate-500 cursor-pointer select-none" title="Defang IOCs in the report">
        <input
          type="checkbox"
          checked={defangOn}
          onChange={e => setDefangOn(e.target.checked)}
          className="accent-cyan-600"
        />
        Defang
      </label>
      <button
        onClick={handleCopy}
        className="px-3 py-1.5 text-xs font-mono border border-[#1e2d4a] text-slate-400 hover:text-cyan-400 hover:border-cyan-700 rounded transition-all"
      >
        {copied ? '✓ Copied' : '⎘ Copy Report'}
      </button>
    </div>
  )
}
